// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webApiKey'] ?? '',
    appId: dotenv.env['webAppId'] ?? '',
    messagingSenderId: dotenv.env['webMessagingSenderId'] ?? '',
    projectId: dotenv.env['webProjectId'] ?? '',
    authDomain: dotenv.env['webAuthDomain'] ?? '',
    storageBucket: dotenv.env['webStorageBucket'] ?? '',
    measurementId: dotenv.env['webMeasurementId'] ?? '',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey'] ?? '',
    appId: dotenv.env['androidAppId'] ?? '',
    messagingSenderId: dotenv.env['androidMessagingSenderId'] ?? '',
    projectId: dotenv.env['androidProjectId'] ?? '',
    storageBucket: dotenv.env['androidStorageBucket'] ?? '',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iosApiKey'] ?? '',
    appId: dotenv.env['iosAppid'] ?? '',
    messagingSenderId: dotenv.env['iosMessagingSenderId'] ?? '',
    projectId: dotenv.env['iosProjectId'] ?? '',
    storageBucket: dotenv.env['iosStorageBucket'] ?? '',
    iosClientId: dotenv.env['iosClientId'] ?? '',
    iosBundleId: dotenv.env['iosBundleId'] ?? '',
  );
}
